# Backstage Software Catalog - System: @k1s0-ts-error/* パッケージ群

# Backstage Catalog のスキーマバージョン
apiVersion: backstage.io/v1alpha1
# エンティティ種別 (System)
kind: System
# エンティティ自身を識別するメタデータ
metadata:
  # System の一意な名前
  name: k1s0-ts-error
  # UI 表示用の説明文
  description: "@k1s0-ts-error/* (core / react / react-native) 共通エラー正規化・分類・通報・通知連携ライブラリ群"
# System 固有の仕様
spec:
  # 所有者 (Group)
  owner: k1s0-framework-team
  # 所属する Domain
  domain: k1s0-framework
