# Backstage Software Catalog - System: @k1s0-ts-config/* パッケージ群

# Backstage Catalog のスキーマバージョン
apiVersion: backstage.io/v1alpha1
# エンティティ種別 (System)
kind: System
# エンティティ自身を識別するメタデータ
metadata:
  # System の一意な名前 (各 Component の system から参照)
  name: k1s0-ts-config
  # UI 表示用の説明文
  description: "@k1s0-ts-config/* (core / react / react-native) 設定管理ライブラリ群"
# System 固有の仕様
spec:
  # 所有者 (Group)
  owner: k1s0-framework-team
  # 所属する Domain
  domain: k1s0-framework
